import {
  AirVent,
  Baby,
  Bath,
  BatteryMedium,
  Bike,
  Bird,
  BookOpen,
  Brush,
  Car,
  Cat,
  Coffee,
  Dog,
  Droplet,
  Dumbbell,
  Fan,
  FileText,
  FireExtinguisher,
  Fish,
  Flower2,
  Fuel,
  Gauge,
  Glasses,
  Hammer,
  HandHelping,
  HeartPulse,
  House,
  IdCard,
  KeyRound,
  Leaf,
  Lightbulb,
  Package,
  PawPrint,
  Pill,
  Plane,
  Refrigerator,
  Scissors,
  Shapes,
  ShieldCheck,
  Shirt,
  Sofa,
  Sparkles,
  SprayCan,
  Sprout,
  Stethoscope,
  Syringe,
  Thermometer,
  Toothbrush,
  WashingMachine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Curated, stable icon keys stored in the database (pattern ^[a-z0-9-]{1,32}$). */
export const ICONS = {
  house: House,
  car: Car,
  sparkles: Sparkles,
  "heart-pulse": HeartPulse,
  "paw-print": PawPrint,
  sprout: Sprout,
  "file-text": FileText,
  "hand-helping": HandHelping,
  shapes: Shapes,
  droplet: Droplet,
  "air-vent": AirVent,
  fan: Fan,
  wrench: Wrench,
  hammer: Hammer,
  "fire-extinguisher": FireExtinguisher,
  zap: Zap,
  lightbulb: Lightbulb,
  battery: BatteryMedium,
  "washing-machine": WashingMachine,
  refrigerator: Refrigerator,
  sofa: Sofa,
  bath: Bath,
  "spray-can": SprayCan,
  gauge: Gauge,
  fuel: Fuel,
  bike: Bike,
  toothbrush: Toothbrush,
  brush: Brush,
  scissors: Scissors,
  glasses: Glasses,
  shirt: Shirt,
  pill: Pill,
  syringe: Syringe,
  stethoscope: Stethoscope,
  thermometer: Thermometer,
  dumbbell: Dumbbell,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  fish: Fish,
  leaf: Leaf,
  flower: Flower2,
  "id-card": IdCard,
  "shield-check": ShieldCheck,
  "key-round": KeyRound,
  plane: Plane,
  "book-open": BookOpen,
  package: Package,
  coffee: Coffee,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;
export const ICON_KEYS = Object.keys(ICONS) as IconKey[];

export function isIconKey(value: unknown): value is IconKey {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(ICONS, value);
}

export function getIcon(key: string | null | undefined): LucideIcon {
  return key && isIconKey(key) ? ICONS[key] : Shapes;
}
